package gConf

import (
	"g-conf/csource"
	"testing"

	"github.com/stretchr/testify/assert"
)

type AutoGenerated struct {
	LogID      string `json:"log_id"`
	ActionRule struct {
		Pos1 []interface{} `json:"pos_1"`
		Pos2 []interface{} `json:"pos_2"`
		Pos3 []interface{} `json:"pos_3"`
	} `json:"action_rule"`
}

func TestReadJson(t *testing.T) {
	c_ptr := New()
	jsonConf := csource.Json{Path: "example/test1.json"}
	myConfig := AutoGenerated{}
	err := c_ptr.AddSource(&jsonConf).AddTo(&myConfig).Trans()
	// log.Println(myConfig)
	assert.NoError(t, err)
}
